### ISSUE TITLE
Registry keys decrypted only partially

### ISSUE THREAD

**Issue by Jusb3** [drole/qakbot-registry-decrypt#1]
First of all thanks for great work on reverse engineering the algorithm!

However, one thing I noticed that when I decrypted some registry values, there is one value decrypted correctly, but there is some unreadable data at the end of each registry value. I noticed that the same issue was on the example data you provided on your blog. Did you find when reverse engineering the sample what this extra data is?

**Comment by drole** [comment]
Hi Jusb3,

it looks like those are garbage data, probably to confuse us

**Comment by Jusb3** [comment]
Yes, I did a bit of reverse engineering myself and can confirm that there is 0-100 pseudorandom bytes added to the end.
